import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CATsite",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Background video with overlay */}
        <section className="video-container relative">
          <video
            autoPlay
            loop
            muted
            playsInline
            className="background-video absolute top-0 left-0 w-full h-full object-cover"
          >
            <source src="/bgvideo.mp4" type="video/mp4" />
          </video>

          {/* Overlay text on video */}
          <div className="video-overlay absolute top-0 left-0 w-full h-full bg-black bg-opacity-75 flex flex-col justify-center items-start text-white p-48">
            <h1 className="text-4xl font-bold mb-4">
              PRECAUTION IS <br /> BETTER THAN CURE
            </h1>
            <p className="text-xl">
              Additional text content can go here,<br /> providing more context or a
              message beneath <br /> the main heading.
            </p>
          </div>

          {/* Overlay content (Navbar) */}
          <div className="content-container relative">
            <Navbar />
          </div>
        </section>

        {/* Children content (Page.js content) */}
        <div className="page-content-container">
          {children}
        </div>
      </body>
    </html>
  );
}
